/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CocosBuilderReader_jsb.ini" on 2012-10-18
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_COCOSBUILDERREADER

#import "js_bindings_NS_manual.h"
#import "CCBReader.h"
#import "CCBAnimationManager.h"

/*
 * CCBAnimationManager
 */
#pragma mark - CCBAnimationManager


#ifdef __cplusplus
extern "C" {
#endif

void JSB_CCBAnimationManager_createClass(JSContext *cx, JSObject* globalObj, const char* name );

// Manually generated methods
JSBool JSB_CCBAnimationManager_setCompletedAnimationCallbackBlock_(JSContext *cx, uint32_t argc, jsval *vp);


extern JSObject *JSB_CCBAnimationManager_object;
extern JSClass *JSB_CCBAnimationManager_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSB_CCBAnimationManager : JSB_NSObject
{
}

@end

/*
 * CCBReader
 */
#pragma mark - CCBReader


#ifdef __cplusplus
extern "C" {
#endif

void JSB_CCBReader_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_CCBReader_object;
extern JSClass *JSB_CCBReader_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSB_CCBReader : JSB_NSObject
{
}

@end


#endif // JSB_INCLUDE_COCOSBUILDERREADER
