/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CocosBuilderReader_jsb.ini" on 2012-10-18
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_COCOSBUILDERREADER

#import "js_bindings_NS_manual.h"
#import "CCBReader.h"
#import "CCBAnimationManager.h"
JSB_CCBReader_createClass(_cx, CocosBuilderReader, "_Reader");
JSB_CCBAnimationManager_createClass(_cx, CocosBuilderReader, "AnimationManager");


#endif // JSB_INCLUDE_COCOSBUILDERREADER
